//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodhiCRM.BLL.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITemplateSMSService")]
    public interface ITemplateSMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemplateSMSService/SendTemplateSMSS", ReplyAction="http://tempuri.org/ITemplateSMSService/SendTemplateSMSSResponse")]
        BodhiCRM.BLL.ServiceReference1.SendTemplateSMSSResponse SendTemplateSMSS(BodhiCRM.BLL.ServiceReference1.SendTemplateSMSSRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemplateSMSService/SendTemplateSMSS", ReplyAction="http://tempuri.org/ITemplateSMSService/SendTemplateSMSSResponse")]
        System.Threading.Tasks.Task<BodhiCRM.BLL.ServiceReference1.SendTemplateSMSSResponse> SendTemplateSMSSAsync(BodhiCRM.BLL.ServiceReference1.SendTemplateSMSSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendTemplateSMSS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendTemplateSMSSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string templateKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string toTel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] sendData;
        
        public SendTemplateSMSSRequest() {
        }
        
        public SendTemplateSMSSRequest(string templateKey, string toTel, string[] sendData) {
            this.templateKey = templateKey;
            this.toTel = toTel;
            this.sendData = sendData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendTemplateSMSSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendTemplateSMSSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendTemplateSMSSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string outMsg;
        
        public SendTemplateSMSSResponse() {
        }
        
        public SendTemplateSMSSResponse(bool SendTemplateSMSSResult, string outMsg) {
            this.SendTemplateSMSSResult = SendTemplateSMSSResult;
            this.outMsg = outMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITemplateSMSServiceChannel : BodhiCRM.BLL.ServiceReference1.ITemplateSMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TemplateSMSServiceClient : System.ServiceModel.ClientBase<BodhiCRM.BLL.ServiceReference1.ITemplateSMSService>, BodhiCRM.BLL.ServiceReference1.ITemplateSMSService {
        
        public TemplateSMSServiceClient() {
        }
        
        public TemplateSMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TemplateSMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemplateSMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemplateSMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodhiCRM.BLL.ServiceReference1.SendTemplateSMSSResponse BodhiCRM.BLL.ServiceReference1.ITemplateSMSService.SendTemplateSMSS(BodhiCRM.BLL.ServiceReference1.SendTemplateSMSSRequest request) {
            return base.Channel.SendTemplateSMSS(request);
        }
        
        public bool SendTemplateSMSS(string templateKey, string toTel, string[] sendData, out string outMsg) {
            BodhiCRM.BLL.ServiceReference1.SendTemplateSMSSRequest inValue = new BodhiCRM.BLL.ServiceReference1.SendTemplateSMSSRequest();
            inValue.templateKey = templateKey;
            inValue.toTel = toTel;
            inValue.sendData = sendData;
            BodhiCRM.BLL.ServiceReference1.SendTemplateSMSSResponse retVal = ((BodhiCRM.BLL.ServiceReference1.ITemplateSMSService)(this)).SendTemplateSMSS(inValue);
            outMsg = retVal.outMsg;
            return retVal.SendTemplateSMSSResult;
        }
        
        public System.Threading.Tasks.Task<BodhiCRM.BLL.ServiceReference1.SendTemplateSMSSResponse> SendTemplateSMSSAsync(BodhiCRM.BLL.ServiceReference1.SendTemplateSMSSRequest request) {
            return base.Channel.SendTemplateSMSSAsync(request);
        }
    }
}
